### ISSUE TITLE
After Firmware Update V2.2.0 access to WebBox is denied 

### ISSUE THREAD

**Issue by chma73** [jpcornil-git/HA-sma#18]
I followed your instructions, but after Firmware Update to V2.2.0 I have no access to the WebBox.
Also the attempt to reinstall the WebBox failed - the login / authorization fails - password etc. is correct, because I have normal access to the WebBox with it. Everything works fine with the previous version. Please help.

**Comment by jpcornil-git** [comment]
There is no login for this integration ... could you drop HA logs, a screenshot, ... to help me to better understand your issue ?

**Comment by jpcornil-git** [comment]
You tried to install the SMA Solar, not the SMA webbox integration
Let me know if this solve your issue

**Comment by chma73** [comment]
ups sorry you are right, but the problem is still there I try tomorrow again and let you know the result

**Comment by jpcornil-git** [comment]
If you still have an issue tomorrow, could you try to run the sma_webbox.py script (located in custom_components/sma_webbox/) and report results 
``` bash
python3 sma_webbox.py <webbox ip_address>
```
or  HomeAssistant logs

**Comment by chma73** [comment]
I could solve the issue, the new entities were hidden and deactivated

**Comment by chma73** [comment]
I could solve the issue, the new entities were hidden and deactivated

**Comment by jpcornil-git** [comment]
Thanks for the feedback/confirmation. New entities are disabled by default and should be added selectively (to avoid creating a bunch of entities you don't always need everytime a new integration is added)
