### ISSUE TITLE
Stopped working since latest update

### ISSUE THREAD

**Issue by aardvarkl** [jpcornil-git/HA-sma#19]
If I run python3 sma_webbox.py <webbox ip_address> from the command line it seems to work
I am running this from the /homeassistant/custom_components/sma_webbox folder

My HA config folder would appear to be /homeassistant/custom_components
Inside this is sma_webbox with the files such as __init__.p[y, config_flow.py const.py sma_webbox.py etc

I tried deleting the existing device, redownloading and refreshing the files from the repository

I cannot get past Set up SMA Solar from the Integrations/Add Integration using any variety of installer/user/Use SSL/Verify SSL which just says "failed to connect"

Any ideas? This worked with the previous version and stopped with the update a few days ago

**Comment by jpcornil-git** [comment]
You probably tried to install the SMA Solar, not the SMA webbox integration (no authentication for this one)

Let me know if this solve your issue

**Comment by aardvarkl** [comment]
That was indeed the issue as to why I couldn't get it to work again.

Thank you

**Comment by jpcornil-git** [comment]
My pleasure, thanks for the confirmation
