### ISSUE TITLE
BatChrgOp value unknown 

### ISSUE THREAD

**Issue by ballydoon** [jpcornil-git/HA-sma#22]
All works great except I get an "Unknown" for the BatChrgOp value.

**Comment by jpcornil-git** [comment]
I suppose that you are talking about an "Unknown" state for the BatChrgOp sensor, not an error/warning reported by homeassistant ?

If the former, then it is likely that your webbox doesn't report the "BatChrgOp" (Battery Charger Operating state ?) sensor, if the latter could you check/add HomeAssistant logs (Settings -> System -> logs) to this issue or better/if you are confortable with homeassistant's terminal run the following command and attach output logs as well ?

``` bash
python3 custom_components/sma_webbox/sma_webbox.py <webbox ip_address>
```

Running the above command is also useful to confirm that the webbox doesn't report anything for that sensor (or that there is effectively an issue to fix with the integration :-)

**Comment by ballydoon** [comment]
I tried the command in terminal but recieved a "command not found".  Couldn't see anything in the log.
If I do an RPC request with an API tester it does return a value either Float, Boost or Equalize.

![Screenshot_20241203-063513](https://github.com/user-attachments/assets/2b35a3e8-83b4-4d30-bafe-576ce4486e48)

Cheers

**Comment by jpcornil-git** [comment]
Interesting, unit is listed with an empty string ... but it shouldn't hurt a priori.

Could you upload a screenshot/log when you run the command above with the "command not found" result as I would like to get/analyze the full log ?

Are you runing HAOS, HA within docker/a container, ... ?

Cheers,
jpc

**Comment by ballydoon** [comment]
I've attached the log file. Doesn't appear readable though.
[home-assistant_sma_webbox_2024-12-03T11-20-53.387Z.log](https://github.com/user-attachments/files/17992133/home-assistant_sma_webbox_2024-12-03T11-20-53.387Z.log)

**Comment by jpcornil-git** [comment]
Issue is, as expected, related to an empty `unit` field; when a unit is associated with data, the code will try to convert it as a float before reporting back to home assistant (only number should be associated with unit) everything else is a string.

Could you edit the file in custom_components/sma_webbox/sensor.py (e.g. using HA File Editor) and replace the line in
https://github.com/jpcornil-git/HA-sma/blob/main/custom_components/sma_webbox/sensor.py#L218
``` python
    def native_value(self) -> StateType:
        """Return the state of the sensor."""
        value = self._data[WEBBOX_REP_VALUE_VALUE]
        try:
            if WEBBOX_REP_VALUE_UNIT in self._data: <======= replace
                value = float(value)
        except ValueError:
            value = None
```
by:
``` python
    def native_value(self) -> StateType:
        """Return the state of the sensor."""
        value = self._data[WEBBOX_REP_VALUE_VALUE]
        try:
            if self._attr_unit_of_measurement:
                value = float(value)
        except ValueError:
            value = None
```
This should fix your issue.

=> once confirmed, I'll make a new release and you will be able to update via HACS

**Comment by ballydoon** [comment]
Yes, that worked. Thanks for your help.

Cheers
Michael

**Comment by jpcornil-git** [comment]
Thanks; I just commited 742bcf0 to fix this, I'll issue a new HACS release based on that later today.

**Comment by jpcornil-git** [comment]
v2.2.1 released => closing
Thanks for your report
