### ISSUE TITLE
integration not loading since HA 2023.5.x 

### ISSUE THREAD

**Issue by vadercent** [jpcornil-git/HA-sma#7]
I upgraded this weekend from 2023.4.6 to 2023.5.2 and noticed this integration gives "Failed to set up"
In the logs I see the following:
```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/sma/__init__.py:137
Integration: SMA Webbox (documentation, issues)
First occurred: 11:09:06 (1 occurrences)
Last logged: 11:09:06

Error setting up entry 172.23.6.50 for sma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/sma/__init__.py", line 137, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, [Platform.SENSOR])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by jpcornil-git** [comment]
This should be addressed already, cfr [v2.1.0 release notes](https://github.com/jpcornil-git/HA-sma/releases/tag/v2.1.0)
=> could you give it a try if not done already and confirm that it is indeed fixed

**Comment by vadercent** [comment]
Hi, a remove and redownload/install from the component eventually solved the problem.

**Comment by jpcornil-git** [comment]
Thanks for the feedback.

Note that [HACS](https://hacs.xyz/) should handle all of this for you, i.e. UI notification when a new release is available as well as removal/installation of custom integrations/lovelace plugins -> recommended over a manual installation.
